
package Formularios;

import Clases.Recursividad;
import java.util.LinkedList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Formulario1 extends javax.swing.JFrame {
    Recursividad oRe;
    int [] arreglo;
    LinkedList linkedString;

    public Formulario1() {
        initComponents();
        setLocationRelativeTo(null);
        oRe = new Recursividad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jTF_Num1 = new javax.swing.JTextField();
        jBut_CalcularFact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLab_Iterarivo = new javax.swing.JLabel();
        jLab_Recursivo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_Num2 = new javax.swing.JTextField();
        jBut_CalcularMCD = new javax.swing.JButton();
        jLab_MCDIterarivo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLab_MCDRecursivo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBut_CalcularMultiRusa = new javax.swing.JButton();
        jLab_RusoIterarivo = new javax.swing.JLabel();
        jLab_RusoRecursivo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBut_CalcularSerie = new javax.swing.JButton();
        jLab_SerieIterarivo = new javax.swing.JLabel();
        jLab_SerieRecursivo = new javax.swing.JLabel();
        jBut_Expresion = new javax.swing.JButton();
        jLab_ExprIterativo = new javax.swing.JLabel();
        jLab_ExpRecursivo = new javax.swing.JLabel();
        jBut_DecABin = new javax.swing.JButton();
        jLab_DecimABinIterativo = new javax.swing.JLabel();
        jLab_DecimABinRecursivo = new javax.swing.JLabel();
        jBut_Sumatoria = new javax.swing.JButton();
        jBut_NumAgimos = new javax.swing.JButton();
        jBut_DatoAleatorio = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTF_TamañoArr = new javax.swing.JTextField();
        jBut_Mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab_Datos = new javax.swing.JTable();
        jBut_SumarArreglo = new javax.swing.JButton();
        jLab_SumaArrayI = new javax.swing.JLabel();
        jLab_SumaArrayR = new javax.swing.JLabel();
        jBut_MaxMin = new javax.swing.JButton();
        jLab_MaxMinArrayI = new javax.swing.JLabel();
        jLab_MaxMinArrayR = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFPalindromo = new javax.swing.JTextField();
        jButtonPalindromo = new javax.swing.JButton();
        jLab_Palindromo = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBut_CalcularFact.setText("FACTORIAL");
        jBut_CalcularFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularFactActionPerformed(evt);
            }
        });

        jLabel1.setText("NUMERO 1:");

        jLabel2.setText("ITERATIVO");

        jLabel3.setText("RECURSIVO");

        jLab_Iterarivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_Iterarivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_Iterarivo.setOpaque(true);

        jLab_Recursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_Recursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_Recursivo.setOpaque(true);

        jLabel4.setText("NUMERO 2:");

        jBut_CalcularMCD.setText("MCD");
        jBut_CalcularMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularMCDActionPerformed(evt);
            }
        });

        jLab_MCDIterarivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_MCDIterarivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_MCDIterarivo.setOpaque(true);

        jLabel5.setText("ITERATIVO");

        jLab_MCDRecursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_MCDRecursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_MCDRecursivo.setOpaque(true);

        jLabel6.setText("RECURSIVO");

        jBut_CalcularMultiRusa.setText("Multi Rusa");
        jBut_CalcularMultiRusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularMultiRusaActionPerformed(evt);
            }
        });

        jLab_RusoIterarivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_RusoIterarivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_RusoIterarivo.setOpaque(true);

        jLab_RusoRecursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_RusoRecursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_RusoRecursivo.setOpaque(true);

        jLabel8.setText("RECURSIVO");

        jLabel9.setText("ITERATIVO");

        jBut_CalcularSerie.setText("Serie");
        jBut_CalcularSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularSerieActionPerformed(evt);
            }
        });

        jLab_SerieIterarivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_SerieIterarivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_SerieIterarivo.setOpaque(true);

        jLab_SerieRecursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_SerieRecursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_SerieRecursivo.setOpaque(true);

        jBut_Expresion.setText("Expresion");
        jBut_Expresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ExpresionActionPerformed(evt);
            }
        });

        jLab_ExprIterativo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_ExprIterativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_ExprIterativo.setOpaque(true);

        jLab_ExpRecursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_ExpRecursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_ExpRecursivo.setOpaque(true);

        jBut_DecABin.setText("Dec A Bin");
        jBut_DecABin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_DecABinActionPerformed(evt);
            }
        });

        jLab_DecimABinIterativo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_DecimABinIterativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_DecimABinIterativo.setOpaque(true);

        jLab_DecimABinRecursivo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_DecimABinRecursivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_DecimABinRecursivo.setOpaque(true);

        jBut_Sumatoria.setText("Sumatoria");
        jBut_Sumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SumatoriaActionPerformed(evt);
            }
        });

        jBut_NumAgimos.setText("Amigos :)");
        jBut_NumAgimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_NumAgimosActionPerformed(evt);
            }
        });

        jBut_DatoAleatorio.setText("Aleatorio");
        jBut_DatoAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_DatoAleatorioActionPerformed(evt);
            }
        });

        jLabel19.setText("Tamaño:");

        jBut_Mostrar.setText("Mostrar");
        jBut_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MostrarActionPerformed(evt);
            }
        });

        jTab_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTab_Datos);

        jBut_SumarArreglo.setText("Suma");
        jBut_SumarArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SumarArregloActionPerformed(evt);
            }
        });

        jLab_SumaArrayI.setBackground(new java.awt.Color(0, 255, 255));
        jLab_SumaArrayI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_SumaArrayI.setOpaque(true);

        jLab_SumaArrayR.setBackground(new java.awt.Color(0, 255, 255));
        jLab_SumaArrayR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_SumaArrayR.setOpaque(true);

        jBut_MaxMin.setText("Max y Min");
        jBut_MaxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MaxMinActionPerformed(evt);
            }
        });

        jLab_MaxMinArrayI.setBackground(new java.awt.Color(0, 255, 255));
        jLab_MaxMinArrayI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_MaxMinArrayI.setOpaque(true);

        jLab_MaxMinArrayR.setBackground(new java.awt.Color(0, 255, 255));
        jLab_MaxMinArrayR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_MaxMinArrayR.setOpaque(true);

        jLabel7.setText("String original:");

        jButtonPalindromo.setText("Es palindromo?");
        jButtonPalindromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalindromoActionPerformed(evt);
            }
        });

        jLab_Palindromo.setBackground(new java.awt.Color(0, 255, 255));
        jLab_Palindromo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_Palindromo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(jTF_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut_CalcularFact))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(jTF_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jBut_CalcularMCD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBut_CalcularSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBut_CalcularMultiRusa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBut_Expresion)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jBut_NumAgimos)
                                                .addComponent(jBut_Sumatoria)
                                                .addComponent(jBut_DecABin)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLab_RusoIterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLab_ExprIterativo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLab_SerieIterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLab_Iterarivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLab_MCDIterarivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLab_DecimABinIterativo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLab_Recursivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLab_MCDRecursivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLab_RusoRecursivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLab_SerieRecursivo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jLab_ExpRecursivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLab_DecimABinRecursivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTF_TamañoArr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBut_DatoAleatorio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBut_Mostrar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jBut_MaxMin))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jBut_SumarArreglo)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLab_MaxMinArrayR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLab_SumaArrayI, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLab_SumaArrayR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLab_MaxMinArrayI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 53, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFPalindromo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPalindromo)
                        .addGap(19, 19, 19)
                        .addComponent(jLab_Palindromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLab_Iterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTF_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBut_CalcularFact)
                                                .addComponent(jLabel1)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTF_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jBut_CalcularMCD)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLab_MCDIterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jBut_CalcularMultiRusa)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLab_Recursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLab_MCDRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8)
                                            .addGap(0, 0, 0)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLab_RusoRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(7, 7, 7)
                                                    .addComponent(jLab_RusoIterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBut_CalcularSerie)
                                    .addComponent(jLab_SerieIterarivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLab_SerieRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLab_ExprIterativo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLab_ExpRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBut_Expresion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBut_Sumatoria)
                            .addComponent(jLab_DecimABinRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLab_DecimABinIterativo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBut_NumAgimos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBut_DecABin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_DatoAleatorio)
                    .addComponent(jLabel19)
                    .addComponent(jTF_TamañoArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut_Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBut_SumarArreglo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLab_SumaArrayR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLab_SumaArrayI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBut_MaxMin)
                    .addComponent(jLab_MaxMinArrayI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLab_MaxMinArrayR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFPalindromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPalindromo))
                    .addComponent(jLab_Palindromo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_CalcularFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularFactActionPerformed
        try{
            int n = Integer.parseInt(this.jTF_Num1.getText());

            this.jLab_Iterarivo.setText(oRe.factorial(n)+"");
            this.jLab_Recursivo.setText(oRe.factorialR(n)+"");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
    }//GEN-LAST:event_jBut_CalcularFactActionPerformed

    private void jBut_CalcularMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularMCDActionPerformed
        try{
            int n1 = Integer.parseInt(this.jTF_Num1.getText());
            int n2 = Integer.parseInt(this.jTF_Num2.getText());

            this.jLab_MCDIterarivo.setText(oRe.mcd(n1, n2)+"");
            this.jLab_MCDRecursivo.setText(oRe.mcdR(n1, n2)+"");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
        
        
    }//GEN-LAST:event_jBut_CalcularMCDActionPerformed

    private void jBut_CalcularMultiRusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularMultiRusaActionPerformed
        try{
        int n1 = Integer.parseInt(this.jTF_Num1.getText());
        int n2 = Integer.parseInt(this.jTF_Num2.getText());
        
        this.jLab_RusoIterarivo.setText(oRe.multiplicacionRusa(n1, n2)+"");
        this.jLab_RusoRecursivo.setText(oRe.multiplicacionRusaR(n1, n2, 0)+"");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
    }//GEN-LAST:event_jBut_CalcularMultiRusaActionPerformed

    private void jBut_CalcularSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularSerieActionPerformed
        try{
            int pos = Integer.parseInt(this.jTF_Num1.getText());
            
            this.jLab_SerieIterarivo.setText(oRe.finobacci(pos));
            this.jLab_SerieRecursivo.setText(oRe.fibonacciR(pos,0,1,"0, 1"));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
    }//GEN-LAST:event_jBut_CalcularSerieActionPerformed

    private void jBut_ExpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ExpresionActionPerformed
        try{
            Double n = Double.parseDouble(this.jTF_Num1.getText());
            int exponente = Integer.parseInt(this.jTF_Num2.getText());
            
            this.jLab_ExprIterativo.setText(oRe.expresion(n, exponente)+"");
            this.jLab_ExpRecursivo.setText(oRe.expresionR(n, exponente)+"");
                    
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
    }//GEN-LAST:event_jBut_ExpresionActionPerformed

    private void jBut_DecABinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_DecABinActionPerformed
        try{
            int n = Integer.parseInt(this.jTF_Num1.getText());
            this.jLab_DecimABinIterativo.setText(oRe.decimABin(n));
            this.jLab_DecimABinRecursivo.setText(oRe.decimABinR(n,""));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
        
    }//GEN-LAST:event_jBut_DecABinActionPerformed

    private void jBut_SumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SumatoriaActionPerformed
        
        try{
            double x = Double.parseDouble(this.jTF_Num1.getText());
            double n = Double.parseDouble(this.jTF_Num2.getText());
            this.jLab_ExprIterativo.setText(oRe.sumatoria(x,n)+"");
            this.jLab_ExpRecursivo.setText(oRe.sumatoriaR(x,n,0,0)+"");
                    
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se acpetan cadenas!!! "+e.getMessage());
        }
    }//GEN-LAST:event_jBut_SumatoriaActionPerformed

    private void jBut_NumAgimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_NumAgimosActionPerformed
        try{
            int n1 = Integer.parseInt(this.jTF_Num1.getText());
            int n2 = Integer.parseInt(this.jTF_Num2.getText());
            
            if(oRe.paresAmig(n1, n2) == true)
                this.jLab_ExprIterativo.setText("Son amigos!!!");
            else
                this.jLab_ExprIterativo.setText("No son amigos :(");
        }catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_jBut_NumAgimosActionPerformed

    public void aleatorio(){
        Random azar = new Random();
        for(int i=0; i<arreglo.length; i++){
            arreglo[i] = azar.nextInt(100)+1;
        }
    }
    
    public void mostrarArreglo(){
        try{
            for(int i=0; i<arreglo.length; i++){
                this.jTab_Datos.setValueAt(arreglo[i], 0, i);
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void jBut_DatoAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_DatoAleatorioActionPerformed
        try{
            arreglo = new int [Integer.parseInt(this.jTF_TamañoArr.getText()+"")];

            DefaultTableModel modelo = (DefaultTableModel)this.jTab_Datos.getModel();
            modelo.setColumnCount(Integer.parseInt(this.jTF_TamañoArr.getText()+""));

            this.aleatorio();
            this.mostrarArreglo();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"No cadena nula!"+ e.toString());
        }
    }//GEN-LAST:event_jBut_DatoAleatorioActionPerformed

    private void jBut_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MostrarActionPerformed
        this.mostrarArreglo();
    }//GEN-LAST:event_jBut_MostrarActionPerformed

    private void jBut_SumarArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SumarArregloActionPerformed
        try{
            this.jLab_SumaArrayI.setText(oRe.sumaArreglo(arreglo)+"");
            this.jLab_SumaArrayR.setText(oRe.sumaArregloR(arreglo,arreglo.length-1,0)+"");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jBut_SumarArregloActionPerformed

    private void jBut_MaxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MaxMinActionPerformed
        int n = arreglo.length-1;
        this.jLab_MaxMinArrayI.setText(oRe.maxMin(arreglo));
        this.jLab_MaxMinArrayR.setText(oRe.maxMinR(arreglo, arreglo[n], arreglo[n], arreglo.length-1));
    }//GEN-LAST:event_jBut_MaxMinActionPerformed

    private void jButtonPalindromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalindromoActionPerformed
        // TODO add your handling code here:
        String stringOr = jTFPalindromo.getText();
        
        String vacio = "";
        String or2 = "";
        for(int i = 0; i < stringOr.length(); i++){
            if(stringOr.charAt(i) != ' ')
                or2 += stringOr.charAt(i);
        }
        
        this.jLab_Palindromo.setText(oRe.palindromo(or2, vacio, or2.length() - 1, false) + "");
    }//GEN-LAST:event_jButtonPalindromoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_CalcularFact;
    private javax.swing.JButton jBut_CalcularMCD;
    private javax.swing.JButton jBut_CalcularMultiRusa;
    private javax.swing.JButton jBut_CalcularSerie;
    private javax.swing.JButton jBut_DatoAleatorio;
    private javax.swing.JButton jBut_DecABin;
    private javax.swing.JButton jBut_Expresion;
    private javax.swing.JButton jBut_MaxMin;
    private javax.swing.JButton jBut_Mostrar;
    private javax.swing.JButton jBut_NumAgimos;
    private javax.swing.JButton jBut_SumarArreglo;
    private javax.swing.JButton jBut_Sumatoria;
    private javax.swing.JButton jButtonPalindromo;
    private javax.swing.JLabel jLab_DecimABinIterativo;
    private javax.swing.JLabel jLab_DecimABinRecursivo;
    private javax.swing.JLabel jLab_ExpRecursivo;
    private javax.swing.JLabel jLab_ExprIterativo;
    private javax.swing.JLabel jLab_Iterarivo;
    private javax.swing.JLabel jLab_MCDIterarivo;
    private javax.swing.JLabel jLab_MCDRecursivo;
    private javax.swing.JLabel jLab_MaxMinArrayI;
    private javax.swing.JLabel jLab_MaxMinArrayR;
    private javax.swing.JLabel jLab_Palindromo;
    private javax.swing.JLabel jLab_Recursivo;
    private javax.swing.JLabel jLab_RusoIterarivo;
    private javax.swing.JLabel jLab_RusoRecursivo;
    private javax.swing.JLabel jLab_SerieIterarivo;
    private javax.swing.JLabel jLab_SerieRecursivo;
    private javax.swing.JLabel jLab_SumaArrayI;
    private javax.swing.JLabel jLab_SumaArrayR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPalindromo;
    private javax.swing.JTextField jTF_Num1;
    private javax.swing.JTextField jTF_Num2;
    private javax.swing.JTextField jTF_TamañoArr;
    private javax.swing.JTable jTab_Datos;
    // End of variables declaration//GEN-END:variables
}
