/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ColaGenerica;
import Clases.Dato;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vale
 */
public class Formulario1 extends javax.swing.JFrame {
    ColaGenerica <Dato> OCG;
    /**
     * Creates new form Formulario1
     */
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinTamaño = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButCrear = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAleatorio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jButInsertar = new javax.swing.JButton();
        jButEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSpinTamaño.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel1.setText("Tamaño");

        jButCrear.setText("CREAR");
        jButCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCrearActionPerformed(evt);
            }
        });

        jButAleatorios.setText("ALEATORIOS");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jTableAleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "NUMERO", "NOMBRE", "COSTO"
            }
        ));
        jScrollPane1.setViewportView(jTableAleatorio);
        if (jTableAleatorio.getColumnModel().getColumnCount() > 0) {
            jTableAleatorio.getColumnModel().getColumn(0).setHeaderValue("NUMERO");
            jTableAleatorio.getColumnModel().getColumn(1).setHeaderValue("NOMBRE");
            jTableAleatorio.getColumnModel().getColumn(2).setHeaderValue("COSTO");
        }

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMostrar);

        jButInsertar.setText("INSERTAR");
        jButInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInsertarActionPerformed(evt);
            }
        });

        jButEliminar.setText("ELIMINAR");
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButInsertar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButCrear)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButAleatorios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButEliminar)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButCrear)
                    .addComponent(jButAleatorios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButInsertar)
                    .addComponent(jButEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarColaDatos(){
        DefaultTableModel modelo =(DefaultTableModel) this.jTableMostrar.getModel();
        modelo.setColumnCount(OCG.numElementos()+1);
        modelo.setRowCount(3);
        
        this.jTableMostrar.setValueAt("NUMERO", 0, 0);
        this.jTableMostrar.setValueAt("NOMBRE", 1, 0);
        this.jTableMostrar.setValueAt("COSTO", 2, 0);
        
        if(!OCG.colaVacia()){
            Dato aux;
            for(int i=1; i<=OCG.numElementos(); i++){
                aux=OCG.eliminar();
                aux.mostrarDato(jTableMostrar, i);
                OCG.insertar(aux);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"no hay elementos para mostrar" );
            modelo.setColumnCount(0);
        }
            
    }
    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        Dato oDato= new Dato();
        oDato.aleatorio(jTableAleatorio);
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCrearActionPerformed
        int tamaño= Integer.parseInt(this.jSpinTamaño.getValue().toString());
        
        OCG= new ColaGenerica(tamaño);
    }//GEN-LAST:event_jButCrearActionPerformed

    private void jButInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInsertarActionPerformed
        // TODO add your handling code here
        int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
        String nombre= this.jTableAleatorio.getValueAt(0, 1).toString();
        double costo=Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
        
        Dato oDato=new Dato(numero, nombre, costo);
        OCG.insertar(oDato);
        this.mostrarColaDatos();
    }//GEN-LAST:event_jButInsertarActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed
        OCG.eliminar();
        this.mostrarColaDatos();
    }//GEN-LAST:event_jButEliminarActionPerformed

    
    public void intercambiarPares(){
        if(OCG.numElementos() >= 2){
            
            for(int i = 0; i < OCG.numElementos(); i++){
                if(i % 2 == 0){
                    OCG.;
                }
            }
        }
        else 
            JOptionPane.showMessageDialog(this, "Se necesitan al menos dos elementos en la cola");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCrear;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JButton jButInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinTamaño;
    private javax.swing.JTable jTableAleatorio;
    private javax.swing.JTable jTableMostrar;
    // End of variables declaration//GEN-END:variables
}
