/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.FiguraGeometrica;
import Clases.FiguraGeometrica.tiposDeFiguras;
import Clases.MetodosFiguras;
import java.awt.HeadlessException;
import java.awt.Shape;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario1
     */
    FiguraGeometrica figura = new FiguraGeometrica();
    MetodosFiguras metodos;
    public Formulario1() {
        initComponents();
        metodos = MetodosFiguras.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFigura = new javax.swing.JPanel();
        jButtonMostrar = new javax.swing.JButton();
        jComboTipoFigura = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAleatorio = new javax.swing.JTable();
        jButtonModificarCoordenadas = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jPanelMostrar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBuscar = new javax.swing.JTable();
        jPanelBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBuscarFigura = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificarElemento = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelFiguraLayout = new javax.swing.GroupLayout(jPanelFigura);
        jPanelFigura.setLayout(jPanelFiguraLayout);
        jPanelFiguraLayout.setHorizontalGroup(
            jPanelFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jPanelFiguraLayout.setVerticalGroup(
            jPanelFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jButtonMostrar.setText("ALEATORIO");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jComboTipoFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RECTANGULO", "OVALO", "CUADRADO", "TRIANGULO" }));
        jComboTipoFigura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboTipoFiguraItemStateChanged(evt);
            }
        });
        jComboTipoFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoFiguraActionPerformed(evt);
            }
        });

        jTableAleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Numero", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTableAleatorio);

        jButtonModificarCoordenadas.setText("MODIFICAR COORDENADAS");
        jButtonModificarCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCoordenadasActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("GUARDAR FIGURA");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre"
            }
        ));
        jTableMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMostrarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMostrar);

        javax.swing.GroupLayout jPanelMostrarLayout = new javax.swing.GroupLayout(jPanelMostrar);
        jPanelMostrar.setLayout(jPanelMostrarLayout);
        jPanelMostrarLayout.setHorizontalGroup(
            jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanelMostrarLayout.setVerticalGroup(
            jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jTableBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre"
            }
        ));
        jTableBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableBuscar);

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PARA VER LA FIGURA HAGA CLICK EN LA QUE QUIERE VISUALIZAR");

        jComboBuscarFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RECTANGULO", "OVALO", "CUADRADO", "TRIANGULO" }));
        jComboBuscarFigura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBuscarFiguraItemStateChanged(evt);
            }
        });
        jComboBuscarFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBuscarFiguraActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por tipo de figura:");

        jButtonEliminar.setText("ELIMINAR SELECCIONADA");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificarElemento.setText("MODIFICAR SELECCIONADA");
        jButtonModificarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarElementoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("BUSCAR FIGURAS");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Modificar desde tabla");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Entrada de figuras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jPanelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(235, 235, 235)
                                        .addComponent(jButtonGuardar)
                                        .addGap(60, 60, 60)
                                        .addComponent(jButtonMostrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboTipoFigura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificarCoordenadas, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonBuscar))
                                    .addComponent(jComboBuscarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonEliminar)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonModificarElemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1065, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonMostrar)
                                    .addComponent(jButtonGuardar))
                                .addGap(28, 28, 28)
                                .addComponent(jComboTipoFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonModificarCoordenadas))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBuscarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscar)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel5)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        // TODO add your handling code here:
        figura.generarFiguraRandom(jTableAleatorio, jComboTipoFigura, jPanelFigura);
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jComboTipoFiguraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboTipoFiguraItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboTipoFiguraItemStateChanged

    private void jComboTipoFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoFiguraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboTipoFiguraActionPerformed

    private void jButtonModificarCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCoordenadasActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada x", "entrada"));
            int y = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada y", "entrada"));
            int altura = Integer.parseInt(JOptionPane.showInputDialog("Introduzca altura", "entrada"));
            int ancho = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada ancho", "entrada"));
            
            tiposDeFiguras figuraNueva = tiposDeFiguras.valueOf(jComboTipoFigura.getSelectedItem().toString());
            figura.modificarFigura(jPanelFigura, figuraNueva, x, y, altura, ancho);
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonModificarCoordenadasActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = (jTableAleatorio.getValueAt(0, 1).toString());
            int numero =(Integer.parseInt(jTableAleatorio.getValueAt(0, 0).toString()));
            Shape fig = figura.getFigura();
            
            FiguraGeometrica figuraAGuardar = new FiguraGeometrica(numero, nombre);
            figuraAGuardar.setFigura(fig);
            metodos.guardar(figuraAGuardar);
            
            metodos.mostrar(jTableMostrar);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTableMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMostrarMouseClicked
        // TODO add your handling code here:
        try{
        metodos.mostrarDibujo(jPanelMostrar, jTableMostrar.getSelectedRow());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jTableMostrarMouseClicked

    private void jTableBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableBuscarMouseClicked

    private void jComboBuscarFiguraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBuscarFiguraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBuscarFiguraItemStateChanged

    private void jComboBuscarFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBuscarFiguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBuscarFiguraActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        try{
        metodos.eliminar(jTableMostrar.getSelectedRow());
        metodos.limpiarPanel(jPanelMostrar);
        metodos.mostrar(jTableMostrar);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarElementoActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada x", "entrada"));
            int y = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada y", "entrada"));
            int altura = Integer.parseInt(JOptionPane.showInputDialog("Introduzca altura", "entrada"));
            int ancho = Integer.parseInt(JOptionPane.showInputDialog("Introduzca coordenada ancho", "entrada"));
            
            tiposDeFiguras figuraNueva = tiposDeFiguras.valueOf(jTableMostrar.getValueAt(jTableMostrar.getSelectedRow(), 1).toString());
            figura.modificarFigura(jPanelMostrar, figuraNueva, x, y, altura, ancho);
            
            int numFigura = Integer.parseInt(jTableMostrar.getValueAt(jTableMostrar.getSelectedRow(), 0).toString());
            String nombre = jTableMostrar.getValueAt(jTableMostrar.getSelectedRow(), 1).toString();
            
            FiguraGeometrica figuraAGuardar = new FiguraGeometrica(numFigura, nombre);
            figuraAGuardar.setFigura(figura.getFigura());

            metodos.modificar(jTableMostrar.getSelectedRow(), figuraAGuardar);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonModificarElementoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        try{
            metodos.mostrar(jTableBuscar, jPanelBuscar, jComboBuscarFigura.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificarCoordenadas;
    private javax.swing.JButton jButtonModificarElemento;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JComboBox<String> jComboBuscarFigura;
    private javax.swing.JComboBox<String> jComboTipoFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelFigura;
    private javax.swing.JPanel jPanelMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAleatorio;
    private javax.swing.JTable jTableBuscar;
    private javax.swing.JTable jTableMostrar;
    // End of variables declaration//GEN-END:variables
}
