/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Dato;
import Clases.ListaEnlazada;
import Clases.Nodo;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario1
     */
    ListaEnlazada<Dato> listaEn = new ListaEnlazada();
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertarIni2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAleatorio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonInsertarIni = new javax.swing.JButton();
        jButtonInsertarFin = new javax.swing.JButton();
        jButtonElimIni = new javax.swing.JButton();
        jButtonElimFin = new javax.swing.JButton();
        jButtonInvertir = new javax.swing.JButton();
        jButtonLista = new javax.swing.JButton();
        jButtonIntercambiar = new javax.swing.JButton();
        jButtonIntercambiar1 = new javax.swing.JButton();
        jButtonParesPorImpares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldInsertarEnTexto = new javax.swing.JTextField();
        jButtonInsertarIni1 = new javax.swing.JButton();
        jButtonInsertarIni3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInt2 = new javax.swing.JTextField();
        jButtonItercambiarMetodo = new javax.swing.JButton();

        jButtonInsertarIni2.setText("Insertar en posicion");
        jButtonInsertarIni2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarIni2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "NUMERO", "NOMBRE", "COSTO"
            }
        ));
        jScrollPane1.setViewportView(jTableAleatorio);

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMostrar);

        jButtonAleatorio.setText("ALEATORIO");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonInsertarIni.setText("INSERTAR AL INICIO");
        jButtonInsertarIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarIniActionPerformed(evt);
            }
        });

        jButtonInsertarFin.setText("INSERTAR AL FINAL");
        jButtonInsertarFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarFinActionPerformed(evt);
            }
        });

        jButtonElimIni.setText("ELIMINAR INICIO");
        jButtonElimIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElimIniActionPerformed(evt);
            }
        });

        jButtonElimFin.setText("ELIMINAR FINAL");
        jButtonElimFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElimFinActionPerformed(evt);
            }
        });

        jButtonInvertir.setText("Invertir con Pila");
        jButtonInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvertirActionPerformed(evt);
            }
        });

        jButtonLista.setText("Invertir con Lista");
        jButtonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaActionPerformed(evt);
            }
        });

        jButtonIntercambiar.setText("Intercambiar 2do y penultimo");
        jButtonIntercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntercambiarActionPerformed(evt);
            }
        });

        jButtonIntercambiar1.setText("Mostrar sin modificar");
        jButtonIntercambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntercambiar1ActionPerformed(evt);
            }
        });

        jButtonParesPorImpares.setText("Pares por Impares");
        jButtonParesPorImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParesPorImparesActionPerformed(evt);
            }
        });

        jLabel1.setText("Posicion en la que insertar:");

        jButtonInsertarIni1.setText("Insertar en posicion");
        jButtonInsertarIni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarIni1ActionPerformed(evt);
            }
        });

        jButtonInsertarIni3.setText("Eliminar en posicion");
        jButtonInsertarIni3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarIni3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion 1");

        jLabel3.setText("Posicion 2");

        jButtonItercambiarMetodo.setText("Intercambiar");
        jButtonItercambiarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItercambiarMetodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInsertarFin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonElimFin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInsertarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonElimIni, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonParesPorImpares)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonIntercambiar1))
                                    .addComponent(jButtonIntercambiar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLista, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonInvertir, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldInsertarEnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonInsertarIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonInsertarIni3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldInt2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonItercambiarMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInsertarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonElimIni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsertarFin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonElimFin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInvertir)
                            .addComponent(jButtonIntercambiar1)
                            .addComponent(jButtonParesPorImpares)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldInt2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonItercambiarMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldInsertarEnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLista)
                            .addComponent(jButtonIntercambiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsertarIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInsertarIni3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarIniActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
        String nombre = this.jTableAleatorio.getValueAt(0, 1).toString();
        double costo = Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
        
        Dato oDato = new Dato(numero, nombre, costo);
        
       listaEn.insertarAlInicio(oDato);
       
       this.mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonInsertarIniActionPerformed

    private void jButtonInsertarFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarFinActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
        String nombre = this.jTableAleatorio.getValueAt(0, 1).toString();
        double costo = Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
        
        Dato oDato = new Dato(numero, nombre, costo);
        
       listaEn.insAlFinal(oDato);
       
       this.mostrarListaSinModificar(jTableMostrar);
    }//GEN-LAST:event_jButtonInsertarFinActionPerformed

    private void jButtonElimIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElimIniActionPerformed
        // TODO add your handling code here:
        listaEn.elimAlInicio();
        this.mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonElimIniActionPerformed

    public void mostrarListaSinModificar(JTable tabla){
        if(listaEn.contNodos() > 0){
        Dato aux; 
        
            int nodos = listaEn.contNodos();
            DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
            
            modelo.setColumnCount(nodos);
            for(int i = 0; i < nodos; i++){
                aux = (Dato)listaEn.getNodo(i).getDato();
                aux.mostrarDato(tabla, i);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "La lista está vacía");
        }

    private void jButtonElimFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElimFinActionPerformed
        // TODO add your handling code here:
        listaEn.elimAlFin();
        this.mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonElimFinActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        // TODO add your handling code here:
        Dato oDato= new Dato();
        oDato.aleatorio(jTableAleatorio);
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvertirActionPerformed
        // TODO add your handling code here:
        listaEn.invertirConPila();
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonInvertirActionPerformed

    private void jButtonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaActionPerformed
        // TODO add your handling code here:
        listaEn.invertirConLista();
        mostrarListaEnlazada();

    }//GEN-LAST:event_jButtonListaActionPerformed

    private void jButtonIntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntercambiarActionPerformed
        // TODO add your handling code here:
        listaEn.intercambiarElemento(2, listaEn.contNodos() - 1);
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonIntercambiarActionPerformed

    private void jButtonIntercambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntercambiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIntercambiar1ActionPerformed

    private void jButtonParesPorImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParesPorImparesActionPerformed
        // TODO add your handling code here:
        listaEn.paresPorImparesRecargado();
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonParesPorImparesActionPerformed

    private void jButtonInsertarIni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarIni1ActionPerformed
        // TODO add your handling code here:
        int posicion = Integer.parseInt(jTextFieldInsertarEnTexto.getText());
        
        int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
        String nombre = this.jTableAleatorio.getValueAt(0, 1).toString();
        double costo = Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
        
        Dato oDato = new Dato(numero, nombre, costo);

        listaEn.añadirEnPosicion(posicion, oDato);
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonInsertarIni1ActionPerformed

    private void jButtonInsertarIni2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarIni2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsertarIni2ActionPerformed

    private void jButtonInsertarIni3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarIni3ActionPerformed
        // TODO add your handling code here:
        int posicion = Integer.parseInt(jTextFieldInsertarEnTexto.getText());
        
        listaEn.eliminarPosicion(posicion);
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonInsertarIni3ActionPerformed

    private void jButtonItercambiarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItercambiarMetodoActionPerformed
        // TODO add your handling code here:
        int posicion = Integer.parseInt(jTextFieldInt1.getText());
        int posicion2 = Integer.parseInt(jTextFieldInt2.getText());
        
        listaEn.intercambiarElementoSinEliminar(posicion, posicion2);
        mostrarListaEnlazada();
    }//GEN-LAST:event_jButtonItercambiarMetodoActionPerformed

    public void mostrarListaEnlazada(){
        
        if(!listaEn.listaVacia()){
            Dato aux = new Dato(); 
            int nodos = listaEn.contNodos();
            DefaultTableModel modelo = (DefaultTableModel)jTableMostrar.getModel();
                        
            modelo.setColumnCount(nodos);
            for(int i = 0; i < nodos; i++){
                aux = listaEn.elimAlInicio();
                aux.mostrarDato(jTableMostrar, i);
                listaEn.insAlFinal(aux);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "La lista está vacía");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonElimFin;
    private javax.swing.JButton jButtonElimIni;
    private javax.swing.JButton jButtonInsertarFin;
    private javax.swing.JButton jButtonInsertarIni;
    private javax.swing.JButton jButtonInsertarIni1;
    private javax.swing.JButton jButtonInsertarIni2;
    private javax.swing.JButton jButtonInsertarIni3;
    private javax.swing.JButton jButtonIntercambiar;
    private javax.swing.JButton jButtonIntercambiar1;
    private javax.swing.JButton jButtonInvertir;
    private javax.swing.JButton jButtonItercambiarMetodo;
    private javax.swing.JButton jButtonLista;
    private javax.swing.JButton jButtonParesPorImpares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAleatorio;
    private javax.swing.JTable jTableMostrar;
    private javax.swing.JTextField jTextFieldInsertarEnTexto;
    private javax.swing.JTextField jTextFieldInt1;
    private javax.swing.JTextField jTextFieldInt2;
    // End of variables declaration//GEN-END:variables
}
