/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.Dato;
import Clases.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario1
     */
    
    Stack stack;
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTamaño = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonPush = new javax.swing.JButton();
        jButtonPop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAleatorio = new javax.swing.JTable();
        jButtonInvertir = new javax.swing.JButton();
        jButtonQuitarFondo = new javax.swing.JButton();
        jTextFieldElemento = new javax.swing.JTextField();
        jButtonPosicion = new javax.swing.JButton();
        jButtonAñadir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamaño:");

        jButtonCrear.setText("CREAR PILA");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonAleatorio.setText("ALEATORIO");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonPush.setText("PUSH");
        jButtonPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPushActionPerformed(evt);
            }
        });

        jButtonPop.setText("POP");
        jButtonPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPopActionPerformed(evt);
            }
        });

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Costo"
            }
        ));
        jScrollPane1.setViewportView(jTableMostrar);

        jTableAleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Costo"
            }
        ));
        jScrollPane2.setViewportView(jTableAleatorio);

        jButtonInvertir.setText("INVERTIR");
        jButtonInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvertirActionPerformed(evt);
            }
        });

        jButtonQuitarFondo.setText("QUITAR FONDO");
        jButtonQuitarFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarFondoActionPerformed(evt);
            }
        });

        jButtonPosicion.setText("Quitar posicion");
        jButtonPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosicionActionPerformed(evt);
            }
        });

        jButtonAñadir.setText("Añadir en posicion");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAleatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPush)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPop))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInvertir)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonQuitarFondo)
                        .addGap(106, 106, 106)
                        .addComponent(jTextFieldElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPosicion)
                            .addComponent(jButtonAñadir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonAleatorio)
                    .addComponent(jButtonPush)
                    .addComponent(jButtonPop))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInvertir)
                            .addComponent(jButtonQuitarFondo)
                            .addComponent(jTextFieldElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPosicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAñadir)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        try{
        int tamaño = Integer.parseInt(jTextFieldTamaño.getText());
        stack = new Stack(tamaño);
        JOptionPane.showMessageDialog(this, "Se creo el objeto pila con exito");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inserte un numero valido en la casilla");
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        // TODO add your handling code here:
        Dato dato = new Dato();
        dato.generarDatosAleatorios(jTableAleatorio);
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPushActionPerformed
        // TODO add your handling code here:
        try{
        int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
        String nombre = this.jTableAleatorio.getValueAt(0, 1).toString();
        double costo = Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
        
        Dato dato = new Dato(numero, nombre, costo);
        
        stack.push(dato);
        stack.mostrar(jTableMostrar);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonPushActionPerformed

    private void jButtonPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPopActionPerformed
        // TODO add your handling code here:
        try{
            stack.pop();
            stack.mostrar(jTableMostrar);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButtonPopActionPerformed

    private void jButtonInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvertirActionPerformed
        // TODO add your handling code here:
        try{
        stack.invertirStack();
        stack.mostrar(jTableMostrar);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonInvertirActionPerformed

    private void jButtonQuitarFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarFondoActionPerformed
        // TODO add your handling code here:
        try{
        stack.popBottomElement();
        stack.mostrar(jTableMostrar);
        }
        catch(NullPointerException e){
         JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonQuitarFondoActionPerformed

    private void jButtonPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosicionActionPerformed
        // TODO add your handling code here:
        try{
            int posicion = Integer.parseInt(jTextFieldElemento.getText());
            stack.eliminarElemento(posicion);
            stack.mostrar(jTableMostrar);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inserte un formato de numero valido");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonPosicionActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
        try{
            int posicion = Integer.parseInt(jTextFieldElemento.getText());
            int numero = Integer.parseInt(this.jTableAleatorio.getValueAt(0, 0).toString());
            String nombre = this.jTableAleatorio.getValueAt(0, 1).toString();
            double costo = Double.parseDouble(this.jTableAleatorio.getValueAt(0, 2).toString());
            
            Dato nuevoDato = new Dato(numero, nombre, costo);
            
            stack.agregaElemento(posicion, nuevoDato);
            stack.mostrar(jTableMostrar);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, e);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e);

        }
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonInvertir;
    private javax.swing.JButton jButtonPop;
    private javax.swing.JButton jButtonPosicion;
    private javax.swing.JButton jButtonPush;
    private javax.swing.JButton jButtonQuitarFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAleatorio;
    private javax.swing.JTable jTableMostrar;
    private javax.swing.JTextField jTextFieldElemento;
    private javax.swing.JTextField jTextFieldTamaño;
    // End of variables declaration//GEN-END:variables
}
